/* Bundles the admin page into the Worker.
 *
 * The admin must not be a file on the public web server. Cloudflare Access can
 * only guard traffic that passes through Cloudflare, so anything sitting on the
 * origin can be fetched directly by anyone who reaches it — which is exactly
 * what happened while a stale DNS entry pointed at the old host.
 *
 * So the page lives inside the Worker, behind Access, and the origin has no
 * /admin at all. Source stays in _admin-src/ and is baked in at deploy time.
 *
 *   node worker/build-assets.mjs      (runs automatically before deploy)
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const read = f => readFileSync(join(root, '_admin-src', f), 'utf8');

const assets = {
  '': { body: read('index.html'), type: 'text/html; charset=utf-8' },
  'admin.css': { body: read('admin.css'), type: 'text/css; charset=utf-8' },
  'admin.js': { body: read('admin.js'), type: 'text/javascript; charset=utf-8' },
};

writeFileSync(
  join(root, 'worker', 'assets.js'),
  '/* Generated by build-assets.mjs — do not edit. Source is in _admin-src/. */\n' +
  'export const ADMIN = ' + JSON.stringify(assets, null, 2) + ';\n'
);

const kb = n => (n / 1024).toFixed(1) + ' KB';
for (const [k, v] of Object.entries(assets)) {
  console.log(`  ${k || 'index.html'}: ${kb(v.body.length)}`);
}
